CREATE USER kratos WITH PASSWORD 'kratos';
CREATE USER openfga WITH PASSWORD 'openfga';
CREATE USER tenants WITH PASSWORD 'tenants';
CREATE USER hooks WITH PASSWORD 'hooks';

CREATE DATABASE kratos;
GRANT ALL PRIVILEGES ON DATABASE kratos TO kratos;
ALTER DATABASE kratos OWNER TO kratos;

CREATE DATABASE openfga;
GRANT ALL PRIVILEGES ON DATABASE openfga TO openfga;
ALTER DATABASE openfga OWNER TO openfga;

CREATE DATABASE tenants;
GRANT ALL PRIVILEGES ON DATABASE tenants TO tenants;
ALTER DATABASE tenants OWNER TO tenants;

CREATE DATABASE hooks;
GRANT ALL PRIVILEGES ON DATABASE hooks TO hooks;
ALTER DATABASE hooks OWNER TO hooks;
