// Package httpclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package httpclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// TenantServiceInviteMemberBody defines model for TenantServiceInviteMemberBody.
type TenantServiceInviteMemberBody struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
}

// TenantServiceProvisionUserBody defines model for TenantServiceProvisionUserBody.
type TenantServiceProvisionUserBody struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
}

// TenantServiceUpdateTenantBody defines model for TenantServiceUpdateTenantBody.
type TenantServiceUpdateTenantBody struct {
	Tenant *struct {
		CreatedAt *string `json:"createdAt,omitempty"`
		Enabled   *bool   `json:"enabled,omitempty"`
		Name      *string `json:"name,omitempty"`
	} `json:"tenant,omitempty"`
	UpdateMask *string `json:"updateMask,omitempty"`
}

// ProtobufAny defines model for protobufAny.
type ProtobufAny struct {
	Type                 *string                `json:"@type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RpcStatus defines model for rpcStatus.
type RpcStatus struct {
	Code    *int32         `json:"code,omitempty"`
	Details *[]ProtobufAny `json:"details,omitempty"`
	Message *string        `json:"message,omitempty"`
}

// TenantCreateTenantRequest defines model for tenantCreateTenantRequest.
type TenantCreateTenantRequest struct {
	Name *string `json:"name,omitempty"`
}

// TenantServiceCreateTenantJSONRequestBody defines body for TenantServiceCreateTenant for application/json ContentType.
type TenantServiceCreateTenantJSONRequestBody = TenantCreateTenantRequest

// TenantServiceUpdateTenantJSONRequestBody defines body for TenantServiceUpdateTenant for application/json ContentType.
type TenantServiceUpdateTenantJSONRequestBody = TenantServiceUpdateTenantBody

// TenantServiceInviteMemberJSONRequestBody defines body for TenantServiceInviteMember for application/json ContentType.
type TenantServiceInviteMemberJSONRequestBody = TenantServiceInviteMemberBody

// TenantServiceProvisionUserJSONRequestBody defines body for TenantServiceProvisionUser for application/json ContentType.
type TenantServiceProvisionUserJSONRequestBody = TenantServiceProvisionUserBody

// Getter for additional properties for ProtobufAny. Returns the specified
// element and whether it was found
func (a ProtobufAny) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProtobufAny
func (a *ProtobufAny) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProtobufAny to handle AdditionalProperties
func (a *ProtobufAny) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["@type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading '@type': %w", err)
		}
		delete(object, "@type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProtobufAny to handle AdditionalProperties
func (a ProtobufAny) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Type != nil {
		object["@type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '@type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// TenantServiceListMyTenants request
	TenantServiceListMyTenants(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TenantServiceListTenants request
	TenantServiceListTenants(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TenantServiceCreateTenantWithBody request with any body
	TenantServiceCreateTenantWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TenantServiceCreateTenant(ctx context.Context, body TenantServiceCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TenantServiceUpdateTenantWithBody request with any body
	TenantServiceUpdateTenantWithBody(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TenantServiceUpdateTenant(ctx context.Context, tenantId string, body TenantServiceUpdateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TenantServiceDeleteTenant request
	TenantServiceDeleteTenant(ctx context.Context, tenantId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TenantServiceInviteMemberWithBody request with any body
	TenantServiceInviteMemberWithBody(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TenantServiceInviteMember(ctx context.Context, tenantId string, body TenantServiceInviteMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TenantServiceListTenantUsers request
	TenantServiceListTenantUsers(ctx context.Context, tenantId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TenantServiceProvisionUserWithBody request with any body
	TenantServiceProvisionUserWithBody(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TenantServiceProvisionUser(ctx context.Context, tenantId string, body TenantServiceProvisionUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TenantServiceListUserTenants request
	TenantServiceListUserTenants(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) TenantServiceListMyTenants(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceListMyTenantsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceListTenants(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceListTenantsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceCreateTenantWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceCreateTenantRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceCreateTenant(ctx context.Context, body TenantServiceCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceCreateTenantRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceUpdateTenantWithBody(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceUpdateTenantRequestWithBody(c.Server, tenantId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceUpdateTenant(ctx context.Context, tenantId string, body TenantServiceUpdateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceUpdateTenantRequest(c.Server, tenantId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceDeleteTenant(ctx context.Context, tenantId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceDeleteTenantRequest(c.Server, tenantId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceInviteMemberWithBody(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceInviteMemberRequestWithBody(c.Server, tenantId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceInviteMember(ctx context.Context, tenantId string, body TenantServiceInviteMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceInviteMemberRequest(c.Server, tenantId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceListTenantUsers(ctx context.Context, tenantId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceListTenantUsersRequest(c.Server, tenantId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceProvisionUserWithBody(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceProvisionUserRequestWithBody(c.Server, tenantId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceProvisionUser(ctx context.Context, tenantId string, body TenantServiceProvisionUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceProvisionUserRequest(c.Server, tenantId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TenantServiceListUserTenants(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTenantServiceListUserTenantsRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewTenantServiceListMyTenantsRequest generates requests for TenantServiceListMyTenants
func NewTenantServiceListMyTenantsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/me/tenants")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTenantServiceListTenantsRequest generates requests for TenantServiceListTenants
func NewTenantServiceListTenantsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenants")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTenantServiceCreateTenantRequest calls the generic TenantServiceCreateTenant builder with application/json body
func NewTenantServiceCreateTenantRequest(server string, body TenantServiceCreateTenantJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTenantServiceCreateTenantRequestWithBody(server, "application/json", bodyReader)
}

// NewTenantServiceCreateTenantRequestWithBody generates requests for TenantServiceCreateTenant with any type of body
func NewTenantServiceCreateTenantRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenants")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTenantServiceUpdateTenantRequest calls the generic TenantServiceUpdateTenant builder with application/json body
func NewTenantServiceUpdateTenantRequest(server string, tenantId string, body TenantServiceUpdateTenantJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTenantServiceUpdateTenantRequestWithBody(server, tenantId, "application/json", bodyReader)
}

// NewTenantServiceUpdateTenantRequestWithBody generates requests for TenantServiceUpdateTenant with any type of body
func NewTenantServiceUpdateTenantRequestWithBody(server string, tenantId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenant.id", runtime.ParamLocationPath, tenantId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenants/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTenantServiceDeleteTenantRequest generates requests for TenantServiceDeleteTenant
func NewTenantServiceDeleteTenantRequest(server string, tenantId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenantId", runtime.ParamLocationPath, tenantId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenants/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTenantServiceInviteMemberRequest calls the generic TenantServiceInviteMember builder with application/json body
func NewTenantServiceInviteMemberRequest(server string, tenantId string, body TenantServiceInviteMemberJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTenantServiceInviteMemberRequestWithBody(server, tenantId, "application/json", bodyReader)
}

// NewTenantServiceInviteMemberRequestWithBody generates requests for TenantServiceInviteMember with any type of body
func NewTenantServiceInviteMemberRequestWithBody(server string, tenantId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenantId", runtime.ParamLocationPath, tenantId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenants/%s/invites", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTenantServiceListTenantUsersRequest generates requests for TenantServiceListTenantUsers
func NewTenantServiceListTenantUsersRequest(server string, tenantId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenantId", runtime.ParamLocationPath, tenantId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenants/%s/users", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTenantServiceProvisionUserRequest calls the generic TenantServiceProvisionUser builder with application/json body
func NewTenantServiceProvisionUserRequest(server string, tenantId string, body TenantServiceProvisionUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTenantServiceProvisionUserRequestWithBody(server, tenantId, "application/json", bodyReader)
}

// NewTenantServiceProvisionUserRequestWithBody generates requests for TenantServiceProvisionUser with any type of body
func NewTenantServiceProvisionUserRequestWithBody(server string, tenantId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenantId", runtime.ParamLocationPath, tenantId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenants/%s/users", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTenantServiceListUserTenantsRequest generates requests for TenantServiceListUserTenants
func NewTenantServiceListUserTenantsRequest(server string, userId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "userId", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s/tenants", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// TenantServiceListMyTenantsWithResponse request
	TenantServiceListMyTenantsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TenantServiceListMyTenantsResponse, error)

	// TenantServiceListTenantsWithResponse request
	TenantServiceListTenantsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TenantServiceListTenantsResponse, error)

	// TenantServiceCreateTenantWithBodyWithResponse request with any body
	TenantServiceCreateTenantWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TenantServiceCreateTenantResponse, error)

	TenantServiceCreateTenantWithResponse(ctx context.Context, body TenantServiceCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*TenantServiceCreateTenantResponse, error)

	// TenantServiceUpdateTenantWithBodyWithResponse request with any body
	TenantServiceUpdateTenantWithBodyWithResponse(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TenantServiceUpdateTenantResponse, error)

	TenantServiceUpdateTenantWithResponse(ctx context.Context, tenantId string, body TenantServiceUpdateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*TenantServiceUpdateTenantResponse, error)

	// TenantServiceDeleteTenantWithResponse request
	TenantServiceDeleteTenantWithResponse(ctx context.Context, tenantId string, reqEditors ...RequestEditorFn) (*TenantServiceDeleteTenantResponse, error)

	// TenantServiceInviteMemberWithBodyWithResponse request with any body
	TenantServiceInviteMemberWithBodyWithResponse(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TenantServiceInviteMemberResponse, error)

	TenantServiceInviteMemberWithResponse(ctx context.Context, tenantId string, body TenantServiceInviteMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*TenantServiceInviteMemberResponse, error)

	// TenantServiceListTenantUsersWithResponse request
	TenantServiceListTenantUsersWithResponse(ctx context.Context, tenantId string, reqEditors ...RequestEditorFn) (*TenantServiceListTenantUsersResponse, error)

	// TenantServiceProvisionUserWithBodyWithResponse request with any body
	TenantServiceProvisionUserWithBodyWithResponse(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TenantServiceProvisionUserResponse, error)

	TenantServiceProvisionUserWithResponse(ctx context.Context, tenantId string, body TenantServiceProvisionUserJSONRequestBody, reqEditors ...RequestEditorFn) (*TenantServiceProvisionUserResponse, error)

	// TenantServiceListUserTenantsWithResponse request
	TenantServiceListUserTenantsWithResponse(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*TenantServiceListUserTenantsResponse, error)
}

type TenantServiceListMyTenantsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *RpcStatus
}

// Status returns HTTPResponse.Status
func (r TenantServiceListMyTenantsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TenantServiceListMyTenantsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TenantServiceListTenantsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *RpcStatus
}

// Status returns HTTPResponse.Status
func (r TenantServiceListTenantsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TenantServiceListTenantsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TenantServiceCreateTenantResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *RpcStatus
}

// Status returns HTTPResponse.Status
func (r TenantServiceCreateTenantResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TenantServiceCreateTenantResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TenantServiceUpdateTenantResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *RpcStatus
}

// Status returns HTTPResponse.Status
func (r TenantServiceUpdateTenantResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TenantServiceUpdateTenantResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TenantServiceDeleteTenantResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *RpcStatus
}

// Status returns HTTPResponse.Status
func (r TenantServiceDeleteTenantResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TenantServiceDeleteTenantResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TenantServiceInviteMemberResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *RpcStatus
}

// Status returns HTTPResponse.Status
func (r TenantServiceInviteMemberResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TenantServiceInviteMemberResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TenantServiceListTenantUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *RpcStatus
}

// Status returns HTTPResponse.Status
func (r TenantServiceListTenantUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TenantServiceListTenantUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TenantServiceProvisionUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *RpcStatus
}

// Status returns HTTPResponse.Status
func (r TenantServiceProvisionUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TenantServiceProvisionUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TenantServiceListUserTenantsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *RpcStatus
}

// Status returns HTTPResponse.Status
func (r TenantServiceListUserTenantsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TenantServiceListUserTenantsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TenantServiceListMyTenantsWithResponse request returning *TenantServiceListMyTenantsResponse
func (c *ClientWithResponses) TenantServiceListMyTenantsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TenantServiceListMyTenantsResponse, error) {
	rsp, err := c.TenantServiceListMyTenants(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceListMyTenantsResponse(rsp)
}

// TenantServiceListTenantsWithResponse request returning *TenantServiceListTenantsResponse
func (c *ClientWithResponses) TenantServiceListTenantsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TenantServiceListTenantsResponse, error) {
	rsp, err := c.TenantServiceListTenants(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceListTenantsResponse(rsp)
}

// TenantServiceCreateTenantWithBodyWithResponse request with arbitrary body returning *TenantServiceCreateTenantResponse
func (c *ClientWithResponses) TenantServiceCreateTenantWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TenantServiceCreateTenantResponse, error) {
	rsp, err := c.TenantServiceCreateTenantWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceCreateTenantResponse(rsp)
}

func (c *ClientWithResponses) TenantServiceCreateTenantWithResponse(ctx context.Context, body TenantServiceCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*TenantServiceCreateTenantResponse, error) {
	rsp, err := c.TenantServiceCreateTenant(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceCreateTenantResponse(rsp)
}

// TenantServiceUpdateTenantWithBodyWithResponse request with arbitrary body returning *TenantServiceUpdateTenantResponse
func (c *ClientWithResponses) TenantServiceUpdateTenantWithBodyWithResponse(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TenantServiceUpdateTenantResponse, error) {
	rsp, err := c.TenantServiceUpdateTenantWithBody(ctx, tenantId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceUpdateTenantResponse(rsp)
}

func (c *ClientWithResponses) TenantServiceUpdateTenantWithResponse(ctx context.Context, tenantId string, body TenantServiceUpdateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*TenantServiceUpdateTenantResponse, error) {
	rsp, err := c.TenantServiceUpdateTenant(ctx, tenantId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceUpdateTenantResponse(rsp)
}

// TenantServiceDeleteTenantWithResponse request returning *TenantServiceDeleteTenantResponse
func (c *ClientWithResponses) TenantServiceDeleteTenantWithResponse(ctx context.Context, tenantId string, reqEditors ...RequestEditorFn) (*TenantServiceDeleteTenantResponse, error) {
	rsp, err := c.TenantServiceDeleteTenant(ctx, tenantId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceDeleteTenantResponse(rsp)
}

// TenantServiceInviteMemberWithBodyWithResponse request with arbitrary body returning *TenantServiceInviteMemberResponse
func (c *ClientWithResponses) TenantServiceInviteMemberWithBodyWithResponse(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TenantServiceInviteMemberResponse, error) {
	rsp, err := c.TenantServiceInviteMemberWithBody(ctx, tenantId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceInviteMemberResponse(rsp)
}

func (c *ClientWithResponses) TenantServiceInviteMemberWithResponse(ctx context.Context, tenantId string, body TenantServiceInviteMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*TenantServiceInviteMemberResponse, error) {
	rsp, err := c.TenantServiceInviteMember(ctx, tenantId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceInviteMemberResponse(rsp)
}

// TenantServiceListTenantUsersWithResponse request returning *TenantServiceListTenantUsersResponse
func (c *ClientWithResponses) TenantServiceListTenantUsersWithResponse(ctx context.Context, tenantId string, reqEditors ...RequestEditorFn) (*TenantServiceListTenantUsersResponse, error) {
	rsp, err := c.TenantServiceListTenantUsers(ctx, tenantId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceListTenantUsersResponse(rsp)
}

// TenantServiceProvisionUserWithBodyWithResponse request with arbitrary body returning *TenantServiceProvisionUserResponse
func (c *ClientWithResponses) TenantServiceProvisionUserWithBodyWithResponse(ctx context.Context, tenantId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TenantServiceProvisionUserResponse, error) {
	rsp, err := c.TenantServiceProvisionUserWithBody(ctx, tenantId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceProvisionUserResponse(rsp)
}

func (c *ClientWithResponses) TenantServiceProvisionUserWithResponse(ctx context.Context, tenantId string, body TenantServiceProvisionUserJSONRequestBody, reqEditors ...RequestEditorFn) (*TenantServiceProvisionUserResponse, error) {
	rsp, err := c.TenantServiceProvisionUser(ctx, tenantId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceProvisionUserResponse(rsp)
}

// TenantServiceListUserTenantsWithResponse request returning *TenantServiceListUserTenantsResponse
func (c *ClientWithResponses) TenantServiceListUserTenantsWithResponse(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*TenantServiceListUserTenantsResponse, error) {
	rsp, err := c.TenantServiceListUserTenants(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTenantServiceListUserTenantsResponse(rsp)
}

// ParseTenantServiceListMyTenantsResponse parses an HTTP response from a TenantServiceListMyTenantsWithResponse call
func ParseTenantServiceListMyTenantsResponse(rsp *http.Response) (*TenantServiceListMyTenantsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TenantServiceListMyTenantsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RpcStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseTenantServiceListTenantsResponse parses an HTTP response from a TenantServiceListTenantsWithResponse call
func ParseTenantServiceListTenantsResponse(rsp *http.Response) (*TenantServiceListTenantsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TenantServiceListTenantsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RpcStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseTenantServiceCreateTenantResponse parses an HTTP response from a TenantServiceCreateTenantWithResponse call
func ParseTenantServiceCreateTenantResponse(rsp *http.Response) (*TenantServiceCreateTenantResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TenantServiceCreateTenantResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RpcStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseTenantServiceUpdateTenantResponse parses an HTTP response from a TenantServiceUpdateTenantWithResponse call
func ParseTenantServiceUpdateTenantResponse(rsp *http.Response) (*TenantServiceUpdateTenantResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TenantServiceUpdateTenantResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RpcStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseTenantServiceDeleteTenantResponse parses an HTTP response from a TenantServiceDeleteTenantWithResponse call
func ParseTenantServiceDeleteTenantResponse(rsp *http.Response) (*TenantServiceDeleteTenantResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TenantServiceDeleteTenantResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RpcStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseTenantServiceInviteMemberResponse parses an HTTP response from a TenantServiceInviteMemberWithResponse call
func ParseTenantServiceInviteMemberResponse(rsp *http.Response) (*TenantServiceInviteMemberResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TenantServiceInviteMemberResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RpcStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseTenantServiceListTenantUsersResponse parses an HTTP response from a TenantServiceListTenantUsersWithResponse call
func ParseTenantServiceListTenantUsersResponse(rsp *http.Response) (*TenantServiceListTenantUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TenantServiceListTenantUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RpcStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseTenantServiceProvisionUserResponse parses an HTTP response from a TenantServiceProvisionUserWithResponse call
func ParseTenantServiceProvisionUserResponse(rsp *http.Response) (*TenantServiceProvisionUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TenantServiceProvisionUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RpcStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseTenantServiceListUserTenantsResponse parses an HTTP response from a TenantServiceListUserTenantsWithResponse call
func ParseTenantServiceListUserTenantsResponse(rsp *http.Response) (*TenantServiceListUserTenantsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TenantServiceListUserTenantsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RpcStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
